### ISSUE TITLE
polymorph showing ic2 platings for wood

### ISSUE THREAD

**Issue by FlmingDraogGming** [AllTheMods/VolcanoBlock#15] opened 2023-07-30 04:27 UTC
The first bug I found appears randomly, I don't know what triggers it. But I've found so far that when I put Oak Logs into my inventory 2x2 crafting grid it will say I can create different items from the mod IC2 classic

The second bug I found was when creating clay. In the quest book it says to put dirt in a barrel full of water, but when doing that it created mud, to create clay you put dust in a barrel full of water. You can place dripstone under mud to "dry" the mud out into clay, but early in starting the pack, the player does not have access to dripstone to my knowledge

1.  ![2023-07-30_00 23 27](https://github.com/AllTheMods/VolcanoBlock/assets/124545670/c45e5296-5cc9-497f-bf3d-31c1889a88fd)

**Comment by billbertking1** [comment] 2023-07-31 01:29
The first "bug" is a feature added by another mod - don't remember which - to help out with recipe conflicts. If you needed to make containment reactor plating, you wouldn't be able to because planks are that recipe - that's a solution. Second bug was already mentioned #10

**Comment by FlmingDraogGming** [comment] 2023-07-31 04:44
I apologize, i should've mentioned it but i forgot too. when i click on the IC2 item to craft it, it will still come out as oak planks

**Comment by oly2o6** [comment] 2023-07-31 19:30
We can take a look into this for you and let you know, but the quest issue is fixed in 1.0.1!

**Comment by Draxial** [comment] 2023-08-27 13:03
This might've been fixed on later releases, I can't reproduce the issue anymore, although you said it's random; since ic2 crafting is a bit weird and it still produces planks, I'll close this for now; if you or anyone have any suggestion on how to fix, please reopen the issue and comment, thank you!

**Closed by Draxial** 2023-08-27 13:03 UTC
Labels: bug
